 services:
  - type: web
    name: linkedin-ai-post-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPEN_ROUTER
        sync: false  # Set this in Render dashboard 